changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: Features 🎉
      labels:
        - feat
    - title: Fixed 
      labels:
        - fix
    - title: Other Changes 🐞
      labels:
        - refactor
        - perf
        - build
        - ci
        - docs
        - types
        - style
        - test